include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

#   exclude:
#     - path/to/excluded/files/**

linter:
  rules:
    exclude:
      -lib/src/header_parser/clang_bindings/clang_constants.dart
