// Copyright (c) 2020, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'binding_string.dart';

/// To store generated String bindings.
class Writer {
  final String header;
  final String dylibIdentifier;
  final String ffiLibraryPrefix;
  final String initFunctionIdentifier;

  final List<BindingString> _bindings = [];

  Writer({
    this.initFunctionIdentifier = 'init',
    this.dylibIdentifier = '_dylib',
    this.ffiLibraryPrefix = 'ffi',
    this.header,
  }) : assert(initFunctionIdentifier != null);
  String generate() {
    final s = StringBuffer();

    // Write file header (if any).
    if (header != null) {
      s.write(header);
      s.write('\n');
    } else {
      // Write default header, in case none was provided.
      s.write('''/// AUTO GENERATED FILE, DO NOT EDIT.
///
/// Generated by `package:ffigen`.
''');
    }

    // Write neccesary imports.
    s.write("import 'dart:ffi' as $ffiLibraryPrefix;\n");
    s.write('\n');

    // Write dylib.
    s.write('/// Holds the Dynamic library.\n');
    s.write('$ffiLibraryPrefix.DynamicLibrary ${dylibIdentifier};\n');
    s.write('\n');
    s.write('/// Initialises the Dynamic library.\n');
    s.write(
        'void $initFunctionIdentifier($ffiLibraryPrefix.DynamicLibrary _$dylibIdentifier){\n');
    s.write('  ${dylibIdentifier} = _$dylibIdentifier;\n');
    s.write('}\n');

    // Write bindings.
    for (final bs in _bindings) {
      s.write(bs.string);
    }

    return s.toString();
  }

  void addBindingString(BindingString b) {
    _bindings.add(b);
  }
}
