// Copyright (c) 2022, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import Foundation

let swiftLogo = """
     .cdOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOdc.     
  .;kXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXk;.  
 'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx' 
'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'
kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOkXWMMMMMMMMMMMMMMMMMMMWk
XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc,l0WMMMMMMMMMMMMMMMMMMX
WMMMMMMMMMMMMMMWKKWMMMMMMMMMMMMMMMMMX: .c0WMMMMMMMMMMMMMMMMW
MMMMMMMMMWXKNMMMNOdONMMMMMMMMMMMMMMMMK,  .oXMMMMMMMMMMMMMMMM
MMMMMMMMMMW0dxKWMWOcckNMMMMMMMMMMMMMMWx.   ,OWMMMMMMMMMMMMMM
MMMMMMMMMMMMXo;cONWXo',dKWMMMMMMMMMMMMX:    .xWMMMMMMMMMMMMM
MMMMMMMMMMMMMW0:.,o0N0:..lOWMMMMMMMMMMWo     .xWMMMMMMMMMMMM
MMMMMMMMMMMMMMMNx' .:x0x' .;xXWWMMMMMMWd.     .kWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMXo.  .co:.  .;ckNMMMMWo       ;KMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMW0c.   .'.     'lONMX:       .dWMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWO:.           .,lc.        cNMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWO:.                      ;XMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWOc.                    :XMMMMMMMMMM
MMMMMW0kKWMMMMMMMMMMMMMMMMWKo'.                 dWMMMMMMMMMM
MMMMMMXd;;lkKNWMMMMMMMMMMMMMWOd;                lXMMMMMMMMMM
MMMMMMMW0c. .';coxkOOOOOkxoc,..                  :KMMMMMMMMM
MMMMMMMMMW0l.                                     cXMMMMMMMM
MMMMMMMMMMMWXx:.                                  .dWMMMMMMM
MMMMMMMMMMMMMMWKxc,.                    .,codxdl;. :XMMMMMMM
WMMMMMMMMMMMMMMMMMNKkoc;'..       ..,:okKWMMMMMMWO:cXMMMMMMW
0MMMMMMMMMMMMMMMMMMMMMMWNXK0OOOOO0KXNWMMMMMMMMMMMMNXWMMMMMM0
lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl
.lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.
  ;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk,  
   .,d0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0d,    
      .:dOXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0d:.      
""";

@objc public class SwiftClass: NSObject {
  @objc public func getLogo() -> String {
    return swiftLogo;
  }

  @objc public var someField = 123;
}
