// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class Bindings {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  Bindings(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  /// Just a test function
  /// heres another line
  int noParam() {
    return (_noParam ??=
        _dylib.lookupFunction<_c_noParam, _dart_noParam>('noParam'))();
  }

  _dart_noParam? _noParam;

  int withPrimitiveParam(
    int a,
    int b,
  ) {
    return (_withPrimitiveParam ??=
        _dylib.lookupFunction<_c_withPrimitiveParam, _dart_withPrimitiveParam>(
            'withPrimitiveParam'))(
      a,
      b,
    );
  }

  _dart_withPrimitiveParam? _withPrimitiveParam;

  ffi.Pointer<ffi.Double> withPointerParam(
    ffi.Pointer<ffi.Int32> a,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> b,
  ) {
    return (_withPointerParam ??=
        _dylib.lookupFunction<_c_withPointerParam, _dart_withPointerParam>(
            'withPointerParam'))(
      a,
      b,
    );
  }

  _dart_withPointerParam? _withPointerParam;
}

typedef _c_noParam = ffi.Int32 Function();

typedef _dart_noParam = int Function();

typedef _c_withPrimitiveParam = ffi.Uint8 Function(
  ffi.Int32 a,
  ffi.Uint8 b,
);

typedef _dart_withPrimitiveParam = int Function(
  int a,
  int b,
);

typedef _c_withPointerParam = ffi.Pointer<ffi.Double> Function(
  ffi.Pointer<ffi.Int32> a,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> b,
);

typedef _dart_withPointerParam = ffi.Pointer<ffi.Double> Function(
  ffi.Pointer<ffi.Int32> a,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> b,
);
