// ignore_for_file: unused_import

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
/// test line 1
/// test line 2
abstract class Constants {
  static const int a = 10;

  /// negative
  static const int b = -1;
}
